website/config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  get 'search/index'

  get 'table/index'
  get 'table/display_report'
  get '/table_save_search' => "table#save_search"
  
  get 'graph/index'
  get 'performances/index'
  
  get 'saved_search/index'
  get '/saved_search_destroy_reoccurence' => "saved_search#destroy_reoccurence"
  get '/saved_search_edit_reoccurence' => "saved_search#edit_reoccurence"
  get '/saved_search/editing_reoccurence' => "saved_search#editing_reoccurence"
  get 'teachings' => 'teachings#index'

  devise_for :users

  root 'search#index'

  resources :table
  resources :saved_search
  resources :performances do
    collection do
      get 'report'
      get 'radar'
      get 'skillmeters'
      get 'list'
      get 'concept'
    end
  end

end

website/app/models/dx_level1.rb
class DxLevel1 < ActiveRecord::Base
  	has_many :learner_level1s
	has_many :dx_level2s
	has_many :end_dxes, :as => :dxable

	def self.search(search)
		where("name LIKE ?", "%#{search}%")
	end
end

website/app/controllers/problems_controller.rb
class ProblemsController < ApplicationController

	# Whenever learner diagnoses are searched for, the user_id MUST be
	# the current user's id - otherwise it will fetch data from other
	# users!!!!

	# You must check whether something is present before performing actions on it,
	# otherwise Rails will complain if it doesn't exist. eg. if !@next.blank?

	##################################################################################
	# Main problem selection page
	##################################################################################
    	def index
		@ldx = LearnerDx.where(:review_list => true, :user_id => current_user.id)		
    	end

	##################################################################################
	# Add to review list - response to AJAX request
	##################################################################################
	def add
	    @l_id = params[:l]
	    @add_dx = LearnerDx.where(:id => @l_id, :user_id => current_user.id).first
	    @add_dx.review_list = true
	    @add_dx.save
	    
	    @html = '<span class="key">Added to review list</span><br/><span class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-minus"></span> Remove from review list</span>'
	    respond_to do |format|
  	    	format.html do
		    render text: @html 
		end
	    end
	end

	##################################################################################
	# Remove from review list - response to AJAX request
	##################################################################################
	def remove
	    @l_id = params[:l]
	    @add_dx = LearnerDx.where(:id => @l_id, :user_id => current_user.id).first
	    @add_dx.review_list = false
	    @add_dx.save
	    
	    @html = '<span class="error">Removed from review list</span><br/><span class="btn btn-success btn-sm"><span class="glyphicon glyphicon-plus"></span> Add to review list</span>'
	    respond_to do |format|
  	    	format.html do
		    render text: @html 
		end
	    end
	end

	##################################################################################
	# Retrieve data for dropdown menus - response to AJAX request
	##################################################################################
	def data

	    # The parameter sent contains the level of the topic clicked (level 1, 2 or 3) and the id for that topic
	    @s = params[:l].split("_")
	    @level = @s[0]
	    @id = @s[1]
	    params[:search_id] = @id.to_i
	    params[:year_level] = current_user.year_of_training
	    @isend = 0

	    # Search for the appropriate data
	    if @level == "l1"
		@next = DxLevel2.where(:dx_level1_id => @id.to_i)
		params[:search_type] = "DxLevel1"
		@keydx = EndDx.dxable_search3(params[:search_id], params[:search_type], params[:year_level])
	    elsif @level == "l2"
	    	@next = DxLevel3.where(:dx_level2_id => @id.to_i)
		if @next.blank?
			params[:search_type] = "DxLevel2"
			@next = EndDx.dxable_search3(params[:search_id], params[:search_type], params[:year_level])
		    	@isend = 1
		end
	    elsif @level == "l3"
		params[:search_type] = "DxLevel3"
	    	@next = EndDx.dxable_search3(params[:search_id], params[:search_type], params[:year_level])
	    end
	    @html= "<div class='subdata' style='margin-left: 50px'>"

	    if !@next.blank?
	    @next.each do |n|
		@html = @html + "<table width='100%'><tr><td>"

		# Create ids in the same manner as the initial param sent (level + id)
	    	if @level == "l1"
		    @i = "l2_" + n.id.to_s
		elsif @level == "l2"
		    if @isend == 1
		        @i = "e_" + n.id.to_s
		    else
		    	@i = "l3_" + n.id.to_s
		    end
		elsif @level == "l3"
		        @i = "e_" + n.id.to_s
		end
	    
		# Code for topics (that are not diagnoses)
		if !@i.include?("e_")
  	    	@html = @html + "<span class='dx-toggle' id='" + @i + "'>" + n.name + "<span class='glyphicon glyphicon-menu-right'></span></span></td></tr></table>"
		else
		    @ldx = LearnerDx.where(:end_dx_id => n.id, :user_id => current_user.id, :review_list => true)
		    if !@ldx.blank?
			@checkbox = " <span class='key'>Already in review list</span>"
		    else
			@checkbox = " <input id='" + n.id.to_s + "' name=id[] value='" + n.id.to_s + "' type='checkbox'></input>"
		    end
		    @html = @html + "<strong>Category " + n.category + "</strong><label for='" + n.name + "'>" + n.name + "</label>" + @checkbox + "</td></tr></table>"
		end
	    end
	    else
		@html = @html + "No diagnoses could be found."
	    end

	    # Code to display key diagnoses if appropriate
 	    if @level == "l1" and (current_user.year_of_training == "1" or current_user.year_of_training == "2")
	    	@keydx.each do |k|
		    @ldx = LearnerDx.where(:end_dx_id => k.id, :user_id => current_user.id, :review_list => true)
		    if !@ldx.blank?
			@checkbox = " <span class='key'>Already in review list</span>"
		    else
			@checkbox = " <input id='" + k.id.to_s + "' name=id[] value='" + k.id.to_s + "' type='checkbox'></input>"
		    end
		    @html = @html + "<table width='100%'><tr><td><strong class='key-strong'>Key condition</strong><label for='" + k.name + "'>" + k.name + "</label>" + @checkbox + "</td></tr></table>"
	    	end
	    end

		
	    # Send AJAX response
	    @html = @html + "</div>"
	    respond_to do |format|
  	    	format.html do
		    render text: @html 
		end
  	    	format.json do
   	    	    render :json => @next
  	    	end
	    end
end
	##################################################################################
	# User select page - now 'Search for cases' page
	##################################################################################
	def user_select
		@noparam = false
		@nofound = false

		if params[:dropdown]
	    		@dxlevel1s = DxLevel1.all
		end

		# Process search term
		if params[:search]
			params[:year_level] = current_user.year_of_training
			if params[:search] == ""
				@noparam = true
			else
				@searchdx = EndDx.dxable_search2(params[:search], params[:year_level])	
			end
			if !@searchdx.present?
				@nofound = true
			end
		end
			
	end

	##################################################################################
	# Displays all diagnoses on the trainee's review list
	##################################################################################
	def review_list
		@pagetype = "list"
		@ldx = LearnerDx.where(:review_list => true, :user => current_user.id)
	end

	##################################################################################
	# Add diagnoses to the review list (data for the actual page)
	##################################################################################
	def review_list_add
		@pagetype = "add"
		@count = 0 
		@noparam = false
		@nofound = false
		
		if params[:dropdown]
	    		@dxlevel1s = DxLevel1.all
		end
		
		# Process search term
		if params[:search]
			params[:year_level] = current_user.year_of_training
			if params[:search] == ""
				@noparam = true
			else
				@already_reviewed = LearnerDx.where(["name LIKE ?", "%#{params[:search]}%"]).where(:review_list => true).where(:user_id => current_user.id)
				@searchdx = EndDx.dxable_search2(params[:search], params[:year_level])	
			end
			if !@searchdx.present?
				@nofound = true
			end
		end

		# Add selected diagnoses to review list and save
		if params[:id]
			@string = EndDx.where(:id => params[:id])
			@string.each do |s|
				@ldx = LearnerDx.where(:end_dx_id => s.id, :user => current_user.id).first
				# If learner dx doesn't exist for this dx, create it
				if @ldx.nil?
					@ldx = LearnerDx.new
					@ldx.name = s.name
					@ldx.end_dx_id = s.id
					@ldx.user_id = current_user.id
					@ldx.cases_attempted = 0
					@ldx.missed_dx = 0
					@ldx.accuracy = 0
					@ldx.correct_dx = 0
					@ldx.excellent_cases = 0
					@ldx.recent_incorrect = 0
					@ldx.recent_correct = 0
					@ldx.recent_excellent = 0
				end
				@ldx.review_list = true
				@ldx.save
				@count = @count + 1
			end
		end

		@ldx = LearnerDx.where(:review_list => true, :user_id => current_user.id)
	end

	##################################################################################
	# Removes selected diagnoses from the review list (data for the actual page)
	##################################################################################
	def review_list_remove
		@pagetype = "remove"
		@count = 0 # Counts the number of diagnoses selected to determine whether the singular or plural of diagnosis should be used
		@nodx = true # If no diagnoses have been selected for removal, no additional text will be displayed
		
		if params[:id]
			@nodx = false
				@string = LearnerDx.where(:id => params[:id], :user_id => current_user.id)
			@string.each do |s|
				s.review_list = false
				s.save
				@count = @count + 1
			end
			if @count == 0
				@count = -1
			end
		end

		@ldx = LearnerDx.where(:review_list => true, :user_id => current_user.id)

	end

	##################################################################################
	# Displays cases for the trainee to write reports on and processes their answers
	# REPORT ANALYSIS PART HERE
	##################################################################################
	def cases
		@learnerinfo = LearnerInfo.where(:user_id => current_user.id).first

		# SYSTEM SELECT - SYSTEM DECIDES WHAT DIAGNOSES TO SHOW #
		if params[:system_select]
			@dx_array = Array.new
			@practice_array = Array.new

			# Clear old report array
			@learnerinfo.report_array.length.times do
				@learnerinfo.report_array.pop
			end

			# Clear old student report array
			@learnerinfo.answers_array.length.times do
				@learnerinfo.answers_array.pop
			end

			# Get diagnoses
			@learnerinfo.spaced_dx = -1
			@spaced = LearnerDx.spaced.where(:user_id => current_user.id).first
			@number = 0

			if @spaced.nil?
				@string = EndDx.dxable_search(current_user.year_of_training).limit(5).order("RANDOM()")
				@number = 5
			else
				@learnerinfo.spaced_dx = @spaced.end_dx_id

website/app/helpers/problems_helper.rb
module ProblemsHelper
end

website/app/views/problems/_dropdown.html.erb
  Level 1: 
<select name="Level 1" id="level1">
    <option></option>
    <% @dxlevel1s.each do |d1| %>
    <option><%= d1.name %></option>
    <% end %>
</select>
<select name="Level 2" class="level2">
<option></option>

</select>

website/app/views/problems/_nav.html.erb
<div class="col-md-12 back">
<%= link_to problems_path do %><span class="glyphicon glyphicon-triangle-left"></span>  Back to Case Selection<% end %>
</div>
<p class="section_title">
<% if @pagetype == "add" %>
Add diagnoses to review list
<% elsif @pagetype == "remove" %>
Remove diagnoses from review list
<% else %>
Review list
<% end %>
</p>
<% if @pagetype == "list" %>
<button type ="button" class ="btn btn-primary disabled btn-sm">Review list</button>
<% else %>
<%= link_to "View review list", review_list_problems_path, class: "btn btn-primary btn-sm" %> 
<% end %>
<% if @pagetype == "add" %>
<button type ="button" class ="btn btn-primary disabled btn-sm">Add diagnoses to review list</button>
<% else %>
<%= link_to "Add diagnoses to review list", review_list_add_problems_path, class: "btn btn-primary btn-sm" %> 
<% end %>
<% if @pagetype == "remove" %>
<button type ="button" class ="btn btn-primary disabled btn-sm">Remove diagnoses from review list</button>
<% else %>
<%= link_to "Remove diagnoses from review list", review_list_remove_problems_path, class: "btn btn-primary btn-sm" %> 
<% end %>

website/app/views/problems/index.html.erb
<!-- Append content in the head tag -->
<% content_for :for_head do %>
	<title>CRISTAL: Case selection</title>
<% end %>
<div class="row" style="padding-top: 30px">
	<div class="col-md-12">
		<span style="font-size: 1.75em">Welcome <%= current_user.firstname %>!</span>
		<br />
		<span style="font-size: 1.5em">Year of training: <%= current_user.year_of_training %></span>
		<p></p>
			Select one of the options below to get started with some radiology practice cases.
		<p></p>

	</div>
</div>
<div class="row" style="max-width: 900px; margin: 0 auto">
	<div class="col-md-4 case-column graylink" style="max-width: 300px; margin: 0 auto">
		<%= link_to user_select_problems_path do %>
		<img src="/assets/userselect.jpg" style="width: 200px; height: 200px" />
		<br />
		<span class="selection_type">Search for cases</span>
		<br/>
		Choose a topic to practise cases from. Topics are based off the RANZCR Radiodiagnosis Curriculum.	
		<% end %>
	</div>
	<div class="col-md-4 case-column graylink" style="max-width: 300px; margin: 0 auto">
		<%= link_to cases_problems_path(:system_select => true) do %>
		<img src="/assets/systemselect.jpg" style="width: 200px; height: 200px" />  
		<br />
		<span class="selection_type">Practise cases</span>
		<br />
		The system will choose cases that are relevant to your current stage of training. As you complete cases, the system will use this information to present you with topics you have had less exposure to and those which you need to practise more.
		<% end %>
	</div>
	<div class="col-md-4 case-column graylink" style="max-width: 300px; margin: 0 auto">
		<% if @ldx.present? %>
			<%= link_to review_list_problems_path do %>
			<img src="/assets/reviewlist.jpg" style="width: 200px; height: 200px" />  
			<br />
			<span class="selection_type">Manage review list</span>
			<br/>
			You can practise cases and add/remove diagnoses from your review list.
			<% end %>
		<% else %>
			<%= link_to review_list_add_problems_path do %>
			<img src="/assets/reviewlist.jpg" style="width: 200px; height: 200px" />  
			<br />
			<span class="selection_type">Create review list</span>
			<br/>
			Add diagnoses that you want to focus on to your review list.
			<% end %>
		<% end %>
			
	</div>
</div>

website/app/views/problems/review_list-single.html.erb
<!-- Append content in the head tag -->
<% content_for :for_head do %>
	<title>Review list</title>
<% end %>

<%= link_to problems_path do %>
<span class="back"><span class="glyphicon glyphicon-triangle-left"></span>  Back to Problem Selection index</span>
<% end %>
	<div style="padding-top: 30px">
	<img src="/assets/reviewlist.jpg" style="width: 200px; height: 200px" />
	<p style="font-size: 20px">
	Add to review list
	</p>
	<p>
	Search for a diagnosis from the RANZCR Radiodiagnosis Curriculum
	</p>
	<p>
	<u>Switch to dropdown menu mode</u>
	</p>
	</div>
	<div style="padding-top: 50px">
	<%= form_tag(review_list_problems_path, :method => "get", id: "search-dx-form") do %>
	<%= text_field_tag :search, params[:search], placeholder: "Enter search term here", style: "width: 300px; height: 33px" %>
	<%= submit_tag "Search", class: "btn btn-primary"%>
	<% end %>
	</div>
<p></p>
<%= f.collection_check_boxes(:end_dx_ids, EndDx.all, :id, :name) do |e| %>
<table class="table">
	<% if @endx.present? %>
		<tr><td>Diagnoses</td></tr>
		<%= e.label class:"label-checkbox" do%>
			<tr><td>
			<%=e.check_box + e.name%>
			</td></tr>
		<% end %>
	<% end %>
	<% if @endx.present? %>
		<tr><td><%= submit_tag("Add to review list") %></td></tr>
	<% end %>
	<% if !@endx.present? %>
		<tr><td>No diagnoses</td></tr>
	<% end %>
</table>
<% end %>

website/app/views/problems/review_list.html.erb
<!-- Append content in the head tag -->
<% content_for :for_head do %>
	<title>CRISTAL: Review list</title>
<% end %>
<script>
$(document).ready(function(){
    $.ajaxSetup({ cache: false });
	var count = 0;
	var buttonHTML = '<input id="submit-button" class="hidden" name="commit" value="Find practise cases" type="submit" style="display: none"></input>';
    	$(document).on('change', 'input[type=checkbox]', function(){
	if ($(this).is(':checked')) {
		$(this).closest('td').addClass('info');  // unchecked	
		count++;
	}
	else {
    		$(this).closest('td').removeClass('info');  // checked
		count--;
	}
	
	if (count == 0) {
		if ($('#submit-label').hasClass('btn btn-primary')) {
			$('#submit-label').removeClass('btn btn-primary');
			$('#submit-label').addClass('btn btn-primary disabled');
			$('#submit-button').remove();
		}
	}
	else if (count > 0) {
		if ($('#submit-label').hasClass('disabled')) {
			$('#submit-label').removeClass('disabled');
			$('#submit-label').after(buttonHTML)
		}
	}
    	}); 
    	$(document).on('click', '#submit-label', function(){
	if (count == 0) {
		alert('ERROR: You must select at least one diagnosis.');
	}
	});
});
</script>
<a href="top"></a>
<div class="row container" style="max-width: 600px; margin: 0 auto">
<%= render :partial => 'nav', :locals => { :pagetype => @pagetype } %>
<p></p></p></p>
<% if @ldx.present? %>
<%= form_tag("/problems/cases", method: "get") do %>
<p><span class="key">Your review list currently contains <%= @ldx.length %> 
		<% if @ldx.length > 1 %>items.
		<% else %>
		item.
		<% end %></span></p>
<p>Select the diagnoses you want to practise and click 'Find practice cases' at the bottom of the page.</p>
<table class="table">
<% @ldx.each do |l| %>
<tr><td>
		<% if l.end_dx.category == "key" %>
			<span class="key-strong">Key diagnosis</span> 
		<% elsif l.end_dx.category == "1" %>
			<strong>Category 1</strong>
		<% elsif l.end_dx.category == "2" %>
			<strong>Category 2</strong>
		<% elsif l.end_dx.category == "3" %>
			<strong>Category 3</strong>
		<% end %>
<%= l.end_dx.l1_name %>
<% if l.end_dx.dxable_type != "DxLevel1" %>
-> <%= l.end_dx.l2_name %>
	<% if l.end_dx.dxable_type == "DxLevel3" %>
	-> <%= l.end_dx.l3_name %>
	<% end %>
<% end %>	
		->	
<%= label_tag(l.name, (l.name)) %>
<%= check_box_tag("id[]", l.end_dx.id, false, :id => l.end_dx.id) %>
</td></tr>
<% end %>
</table>
<label for="submit-button" class="btn btn-primary disabled" id="submit-label"><i class="glyphicon glyphicon-search"></i> Find practice cases</label>
<p></p><p><a href="#top">Click here to go back to top</a></p>
<% end %>
<% else %>
<table height="20px"><tr><td></td></tr></table>
<p>Your review list is empty.</p><p> <%= link_to "Click here", review_list_add_problems_path %> to add some diagnoses to your review list.</p>
<% end %>
</div>

website/app/views/problems/review_list_a.html.erb
<!-- Append content in the head tag -->
<% content_for :for_head do %>
	<title>Review list</title>
<% end %>
<%= render "nav" %>
<p style="padding-top: 100px">
Diagnoses successfully added. 
</p>
<p><%= link_to "Click here", review_list_problems_path %> to return to your review list or <%= link_to "add more diagnoses to your review list", review_list_add_problems_path %>.</p>

website/app/views/problems/review_list_r.html.erb
<!-- Append content in the head tag -->
<% content_for :for_head do %>
	<title>Review list</title>
<% end %>

<%= link_to problems_path do %>
<span class="back"><span class="glyphicon glyphicon-triangle-left"></span>  Back to Problem Selection index</span>
<% end %>
<p></p>
<%= render "nav" %>
<p style="padding-top: 100px">
<% if @nodx == true %>
No diagnoses were selected for removal.
<% else %>
Diagnoses successfully removed. 
<% end %>
</p>
<% if @ldx.present? %>
<p><%= link_to "Click here", review_list_problems_path %> to return to your review list or <%= link_to "remove more diagnoses from your review list", review_list_remove_problems_path %>.</p>
<% else %>
<p>Your review list is empty.</p><p> <%= link_to "Click here", review_list_add_problems_path %> to add some diagnoses to your review list.</p>
<% end %>

website/app/views/problems/review_list_remove.html.erb
<!-- Append content in the head tag -->
<% content_for :for_head do %>
	<title>Review list</title>
<% end %>
<script>
$(document).ready(function(){
	var count = 0;
	var buttonHTML = '<input id="submit-button" class="hidden" name="commit" value="Add to review list" type="submit" style="display: none"></input>';
    	$(document).on('change', 'input[type=checkbox]', function(){
	if ($(this).is(':checked')) {
		$(this).closest('td').addClass('danger');  // unchecked	
		count++;
	}
	else {
    		$(this).closest('td').removeClass('danger');  // checked
		count--;
	}
	if (count == 0) {
		if ($('#submit-label').hasClass('btn btn-danger')) {
			$('#submit-label').removeClass('btn btn-danger');
			$('#submit-label').addClass('btn btn-danger disabled');
			$('#submit-button').remove();
		}
	}
	else if (count > 0) {
		if ($('#submit-label').hasClass('disabled')) {
			$('#submit-label').removeClass('disabled');
			$('#submit-label').after(buttonHTML)
		}
	}

    	}); 
    	$(document).on('click', '#submit-label', function(){
	if (count == 0) {
		alert('ERROR: You must select at least one diagnosis.');
	}
	}); 
});
</script>
<a href="top"></a>
<div class="row container" style="max-width: 600px; margin: 0 auto">
<%= render :partial => 'nav', :locals => { :pagetype => @pagetype } %>
<p></p>
<p>
<% if @count == 1 %>
<span class="key">Diagnosis successfully removed.</span>
<% elsif @count > 1 %>
<span class="key">Diagnoses successfully removed.</span>
<% elsif @count == -1 %>
<span class="error">ERROR: No diagnoses were selected for removal.</span>
<% end %>
</p>
<% if @ldx.present? %>
<%= form_tag("/problems/review_list_remove", method: "get") do %>
<p>Select the diagnoses you want to remove and click 'Remove from review list' at the bottom of the page.</p>
<table class="table">
	<% @ldx.each do |l| %>
		<tr><td>
		<% if l.end_dx.category == "key" %>
			<span class="key-strong">Key diagnosis</span> 
		<% elsif l.end_dx.category == "1" %>
			<strong>Category 1</strong>
		<% elsif l.end_dx.category == "2" %>
			<strong>Category 2</strong>
		<% elsif l.end_dx.category == "3" %>
			<strong>Category 3</strong>
		<% end %>
<%= l.end_dx.l1_name %>
<% if l.end_dx.dxable_type != "DxLevel1" %>
-> <%= l.end_dx.l2_name %>
	<% if l.end_dx.dxable_type == "DxLevel3" %>
	-> <%= l.end_dx.l3_name %>
	<% end %>
<% end %>	
		->	
		<%= label_tag(l.id, (l.name)) %>		
		<%= check_box_tag("id[]", l.id, false, :id => l.id) %>

		</td></tr>
	<% end %>
	</table>
	<label for="submit-button" class="btn btn-danger disabled" id="submit-label"><i class="glyphicon glyphicon-minus"></i> Remove from review list</label>
	<p></p><p><a href="#top">Click here to go back to top</a></p>
<% end %>
<% else %>
<table height="20px"><tr><td></td></tr></table>
<p>Your review list is empty.</p>  <p><%= link_to "Click here", review_list_add_problems_path %> to add some diagnoses to your review list.</p>
<% end %>
</div>

website/app/views/problems/user_select2.html.erb
<!-- Append content in the head tag -->
<% content_for :for_head do %>
	<title>Case selection</title>
<% end %>

<%= link_to problems_path do %>
<span class="back"><span class="glyphicon glyphicon-triangle-left"></span>  Back to Problem Selection index</span>
<% end %>
	<div style="padding-top: 30px">
	<img src="/assets/userselect.jpg" style="width: 200px; height: 200px" />
	<p style="font-size: 20px">
	User select
	</p>
	<p>
	Search for a topic or diagnosis from the RANZCR Radiodiagnosis Curriculum
	</p>
	<p>
	<u>Switch to dropdown menu mode</u>
	</p>
	</div>
	<div style="padding-top: 50px">
	<%= form_tag(user_select_problems_path, :method => "get", id: "search-dx-form") do %>
	<%= text_field_tag :search, params[:search], placeholder: "Enter search term here", style: "width: 300px; height: 33px" %>
	<%= submit_tag "Search", class: "btn btn-primary"%>
	<% end %>
	</div>
<p></p>
<table class="table" width="500">

	<% if @dx1.present? %>
		<% @dx1.each do |d1| %>
		<tr><td><%= d1.name %></td></tr>
		<% end %>
	<% end %>
	<% if @dx2.present? %>
		<% @dx2.each do |d2| %>
		<tr><td><%= d2.dx_level1.name %> -> <%= d2.name %></td></tr>
		<% end %>
	<% end %>
	<% if @dx3.present? %>
		<% @dx3.each do |d3| %>
		<tr><td><%= d3.dx_level2.dx_level1.name %> -> <%= d3.dx_level2.name %> -> <%= d3.name %></td></tr>
		<% end %>
	<% end %>
	<% if @endx.present? %>
		<% @endx.each do |e| %>

		<tr><td> <%= e.dxable.name %> -> <%= e.name %></td></tr>

		<% end %>
	<% end %>
	<% if (!@dx1.present? and !@dx2.present? and !@dx3.present? and !@endx.present?) %>
		<tr><td>No posts found</td></tr>
	<% end %>
</table>
<p></p>
</div>