website/config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  get 'search/index'

  get 'table/index'
  get 'table/display_report'
  get '/table_save_search' => "table#save_search"
  
  get 'graph/index'
  get 'performances/index'
  
  get 'saved_search/index'
  get '/saved_search_destroy_reoccurence' => "saved_search#destroy_reoccurence"
  get '/saved_search_edit_reoccurence' => "saved_search#edit_reoccurence"
  get '/saved_search/editing_reoccurence' => "saved_search#editing_reoccurence"
  get 'teachings' => 'teachings#index'

  devise_for :users

  root 'search#index'

  resources :table
  resources :saved_search
  resources :performances do
    collection do
      get 'report'
      get 'radar'
      get 'skillmeters'
      get 'list'
      get 'concept'
    end
  end

end

website/app/models/saved_search.rb
class SavedSearch < ActiveRecord::Base
	validates :query, :time, presence: true
	belongs_to :user
end

website/app/controllers/saved_search_controller.rb
class SavedSearchController < ApplicationController
	def index
		# get the saved searches and reoccurences of this user, it will be displayed
		@savedSearches = current_user.saved_searches
		@reoccurences = current_user.reoccurences

		# For each reoccurence, since we do not actaully repeat the search periodically,
		# everytime the  user visit this page we need to create those missing saved search
		# create all the missing savedsearch according to the reoccurence and existing savedSearches
		today = DateTime.now.to_date
		@reoccurences.each do |reoccurence|
			# if the unit is day
			if reoccurence.unit.downcase == "day" || reoccurence.unit.downcase == "days"
				# from the time this reoccurence is last updated to today
				for date in reoccurence.time.to_date..today
					# if it is a date that the search should be repeated and saved,
					# and that day is not the last updated date for the reoccurence
					if (date - reoccurence.time.to_date)%reoccurence.interval == 0 && date != reoccurence.time.to_date
						# check if this search is already saved 
						saved = false
						@savedSearches.each do |savedSearch|
							if savedSearch.time.to_date == date
								saved = true
							end
						end
						# if this search is not already saved, then create a new saved_searches and save it
						if !saved
							current_user.saved_searches.create(:query => reoccurence.query, :time => DateTime.parse(date.to_s))
						end
					end
				end
			end

			# if the unit is week
			if reoccurence.unit.downcase == "week" || reoccurence.unit.downcase == "weeks"
				# from the time this reoccurence is last updated to today
				for date in reoccurence.time.to_date..today
					# if it is a date that the search should be repeated and saved,
					# and that day is not the last updated date for the reoccurence
					if (date - reoccurence.time.to_date)%(7*reoccurence.interval) == 0 && date != reoccurence.time.to_date
						# check if this search is already saved 
						saved = false
						@savedSearches.each do |savedSearch|
							if savedSearch.time.to_date == date
								saved = true
							end
						end
						# if this search is not already saved, then create a new saved_searches and save it
						if !saved
							current_user.saved_searches.create(:query => reoccurence.query, :time => DateTime.parse(date.to_s))
						end
					end
				end
			end

			# if the unit is month
			# month is different, if the user start the reoccurence at 31st of some month, 
			# then next month may not have the 31st, in that case I will save the search at the last day: 28th, 29th or 30th
			if reoccurence.unit.downcase == "month" || reoccurence.unit.downcase == "months"
				date = reoccurence.created_at.to_date
				c = 1
				# if it is a date that the search should be repeated and saved,
				# and that day is not the last updated date for the reoccurence
				while date>>c <= DateTime.now.to_date && (date>>c)>reoccurence.time.to_date
					# check if this search is already saved 
					saved = false
					@savedSearches.each do |savedSearch|
						if savedSearch.time.to_date == date>>c
							saved = true
						end
					end
					# if this search is not already saved, then create a new saved_searches and save it
					if !saved
						current_user.saved_searches.create(:query => reoccurence.query, :time => DateTime.parse((date>>c).to_s))
					end
					c+=1
				end
			end

			# update the last updated date for this reoccurence
			reoccurence.time = DateTime.new(DateTime.now.year,DateTime.now.month,DateTime.now.day)				
			
		end
	end

	# destroy saved search
	def destroy
		@saved_search = SavedSearch.find(params[:id])
	    @saved_search.destroy

	    #stay in the same page
		redirect_to :back
	end

	# destroy reoccurence
	def destroy_reoccurence
		@reoccurence = Reoccurence.find(params[:id])
	    @reoccurence.destroy

	    #stay in the same page
		redirect_to :back
	end
	
	# Go to the edit_reoccurence page which can be used to wither create or edit reoccurence
	def edit_reoccurence
		# title of edit_reoccurence page that will be displayed
		@title = params[:title]
		# below will be auto filled in the edit_reoccurence page.
		# If absent then the corresponding box in edit_reoccurence will be blank
		@query = params[:query]
		@interval = params[:interval]
		@unit = params[:unit]
		# the id of the reoccurence, used in editing_reoccurence method below
		@id = params[:id]
	end
	def editing_reoccurence
		# If you are not editing reoccurence but creating reoccurence then don't destroy anything
		if params[:id].present?
			@reoccurence = Reoccurence.find(params[:id])
		    @reoccurence.destroy
		end

		#create and save that new reoccurences
		query = params[:query]
		interval = params[:interval]
		unit = params[:unit]
		time = DateTime.now
		current_user.reoccurences.create(:query => query, :interval => interval, :unit => unit, :time => DateTime.now)

		# redirect back to the saved search and reoccurences page,
		redirect_to action: "index"
	end
end

website/app/helpers/saved_search_helper.rb
module SavedSearchHelper
end

website/app/views/saved_search/edit_reoccurence.html.erb
<div style="padding: 10px">
	<div style="border: 5px solid #99CCFF; border-radius: 25px; width: 600px; margin: 0 auto;">

		<h2 style="padding-top: 5px;"><%=@title%></h2>

		<form action="/saved_search/editing_reoccurence" style="vertical-align: middle; width: 450px;">
			<div style="padding-top: 10px;">
				<input name="query" value="<%=@query%>" type="text" class="form-control" placeholder="Enter query..." required pattern=".*\S+.*" autofocus>
			</div>
			<div style="padding-top: 15px;">
				<input name="interval" value="<%=@interval%>" type="number" min="1" class="form-control" placeholder="Enter re-occurence interval (e.g. 3, 12)..." required pattern=".*\S+.*">
			</div>
			<div style="padding-top: 15px;">
				<input name="unit" value="<%=@unit%>" type="text" class="form-control" placeholder="Enter re-occurence interval unit (day, week or month)..." required pattern=".*\S+.*">
			</div>
			<div style="padding-top: 15px;">
				<input id="search-button" style="width: 100%;" type="submit" class="btn btn-default" value="Done"/>
			</div>
			<!--User won't see this, this is the id of reoccurence to enable editing-->
			<div style="padding-top: 5px; display: none;">
				<input name="id" value="<%=@id%>" type="text" class="form-control">
			</div>
			<!--User won't see this, this is for returning to where user come form-->
			<div style="padding-top: 5px; display: none;">
				<input name="from" value="<%=@form%>" type="text" class="form-control">
			</div>
		</form>

		<div style="padding: 20px"></div>
	</div>
</div>

website/app/views/saved_search/index.html.erb
<!-- Append content in the head tag -->
<% content_for :for_head do %>
	<title>Repeat searches and saved searches</title>
<% end %>

<div class="container-fluid" style="width: 80%; margin-bottom: 100px">

	<!-- repeating search table -->
	<h1>Repeating searches</h1>
	<!-- button to add new repeating search -->
	<div style="float: right; display: inline; margin-right: 5px;">
		<%= link_to saved_search_edit_reoccurence_path(:title => "Add New Repeating Search", :query => "", :interval => "1", :unit => "month") do %>
			<i class="glyphicon glyphicon-plus"></i>
			Add new repeating search
		<% end %>
	</div>
	
	<!-- repeating search table -->
	<table class="table table-striped table-bordered table-hover">
		<tr>
			<th style="width: 100px;">Date</th>
			<th>Query</th>
			<th style="width: 140px;">Repeat Frequency</th>
			<th style="width: 30px;">Edit</th>
			<th style="width: 98px;">Search Now</th>
			<th style="width: 104px;">See Analysis</th>
			<th style="width: 30px;">Delete</th>
		</tr>
		<% @reoccurences.each do |reoccurence| %>
			<tr>
				<td><%= reoccurence.created_at.to_date %></td>
				<td align="left"><%= reoccurence.query %></td>
				<td><%= reoccurence.interval %> <%= reoccurence.unit %></td>
				<td><!--Edit Reoccurence Setting-->
					<%= link_to saved_search_edit_reoccurence_path(:title => "Edit Repeating Search", :query => reoccurence.query, :interval => reoccurence.interval, :unit => reoccurence.unit, :id => reoccurence.id, :from => "saved_search") do %>
						<i class="glyphicon glyphicon-edit"></i>
					<% end %>
				</td>
				<td><!--View Results (All dates)-->
					<%= link_to table_index_path(:q => reoccurence.query, :time => DateTime.now) do %>
						<i class="glyphicon glyphicon-list" title="View the saved results (the results of this search query when you save this search)"></i>
					<% end %>
				</td>
				<td><!--View analysis (All dates)-->
					<%= link_to graph_index_path(:q => reoccurence.query, :time => DateTime.now) do %>
						<i class="glyphicon glyphicon-signal"></i>
					<% end %>
				</td>
				<td><!--Delete the reoccurence-->
					<%= link_to saved_search_destroy_reoccurence_path(:id => reoccurence.id), :confirm => 'Are you sure you want to delete this?' do %>
						<i style="color: #d9534f;" class="glyphicon glyphicon-remove"></i>
					<% end %>
				</td>
			</tr>
		<% end %>
	</table>

	<!-- vertical spacing -->
	<div style="padding-top: 20px;">&nbsp</div>

	<!-- saved search table -->
	<h1>Saved searches</h1>
	<div style="display: inline;">&nbsp</div>	<!-- There's a div under repeating search header so I have one here too -->
	<table class="table table-striped table-bordered">
		<tr>
			<th style="width: 100px;">Date</th>
			<th>Query</th>
			<th style="width: 110px;">Search Again</th>
			<th style="width: 90px;">Set Repeat</th>
			<th style="width: 90px;">See Result</th>
			<th style="width: 104px;">See Analysis</th>
			<th style="width: 30px;">Delete</th>
		</tr>
		<% @savedSearches.each do |savedSearch| %>
			<tr>
				<td><%= savedSearch.time.to_date %></td>
				<td align="left"><%= savedSearch.query %></td>
				<td><!--Search again (All dates)-->
					<%= link_to table_index_path(:q => savedSearch.query, :time => DateTime.now) do %>
						<i class="glyphicon glyphicon-search" title="Search again now for the most recent results"></i>
					<% end %>
				</td>
				<td><!-- Set repeat with default interval 1 month and query auto filled in -->
					<%= link_to saved_search_edit_reoccurence_path(:title => "Add New Repeating Search", :query => savedSearch.query, :interval => "1", :unit => "month", :id => nil, :from => "saved_search") do %>
						<i class="glyphicon glyphicon-time"></i>
					<% end %>
				</td>
				<td><!--View Results (before certain date)-->
					<%= link_to table_index_path(:q => savedSearch.query, :time => savedSearch.time) do %>
						<i class="glyphicon glyphicon-list" title="View the saved results (the results of this search query when you save this search)"></i>
					<% end %>
				</td>
				<td><!--View analysis (before certain date)-->
					<%= link_to graph_index_path(:q => savedSearch.query, :time => savedSearch.time) do %>
						<i class="glyphicon glyphicon-signal"></i>
					<% end %>
				</td>
				<td><!--Delete the saved search-->
					<%= link_to saved_search_path(savedSearch), :confirm => 'Are you sure you want to delete this?', :method => :delete do %>
						<i style="color: #d9534f;" class="glyphicon glyphicon-remove"></i>
					<% end %>
				</td>
			</tr>
		<% end %>
	</table>
</div>